//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.ModelDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarter
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
